### ISSUE TITLE
Screenshots of use needed

### ISSUE THREAD

**Issue by paul-hammant** [qwefgh90/bside#29]

**Comment by qwefgh90** [comment]
@paul-hammant Hello.
Do you mean screenshots of use are needed in README or somewhere?
Is it something like a guide for new users? Right?

**Comment by paul-hammant** [comment]
People that are intrigued would want to see screenshots. Readme is best. https://www.makeareadme.com/ talks about the importance of screenshots

**Comment by qwefgh90** [comment]
I decided to update README. Thank you for letting me know that guide.

**Comment by paul-hammant** [comment]
Excellent.
